#!/usr/bin/env bash
# Script to build ZynthianOS
# The start Script for this module
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########

set -x
alias bash='bash -x'

export DEBIAN_FRONTEND="noninteractive"
# Update apt package list
apt-get -yy update

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

# Install needed packages
apt-get -y install git wget

# Prepare dirs
sudo -u pi mkdir -p /home/pi/build
ln -s /home/pi /zynthian
rm -rf /usr/lib/lv2
mkdir -p /zynthian/zynthian-plugins/lv2
ln -s /usr/lib/lv2 "/zynthian/zynthian-plugins/lv2"

# Find out zynthian repo url from source line
zynthbox_repo_base_url=$(echo $ZYNTHIANOS_ZYNTHBOX_REPO_SOURCELINE | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*")
# Find out release name from source line
zynthbox_repo_release_name=$(echo $zynthbox_repo_base_url | awk -F"/" '{print $NF}')
# Find out latest zynthian-sys deb version from package list
zynthian_sys_deb_version=$(curl -Ls "$zynthbox_repo_base_url/$zynthbox_repo_release_name.list" | grep zynthian-sys | head -n 1 | sed "s/ //g")
pushd /home/pi/build
    wget "$zynthbox_repo_base_url/pool/main/z/zynthian-sys/$zynthian_sys_deb_version.deb"
    dpkg -i $zynthian_sys_deb_version.deb
    pushd /home/pi/zynthian-sys/scripts
        bash -x setup_system_rbpi_raspbian_lite_bookworm.sh
    popd
popd

# Cleanup build directory
rm -rf /home/pi/build
rm -f /home/pi/README

# Copy Soundfonts
unpack /filesystem/soundfonts /zynthian/zynthian-data/soundfonts

# Make root password raspberry
echo root:raspberry | chpasswd

# Allow SSH root login
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
sed -i 's/PermitRootLogin without-password//g' /etc/ssh/sshd_config

# Disable User Pi
passwd -l pi

