#!/usr/bin/env bash
# Script to build ZynthianOS
# The start Script for this module
# Written by Guy Sheffer <guysoft at gmail dot com>
# GPL V3
########

set -x
alias bash='bash -x'

export DEBIAN_FRONTEND="noninteractive"
# Update apt package list
apt-get -yy update

# Source error handling, leave this in place
source /common.sh
install_cleanup_trap

unpack /filesystem/home/pi /home/pi pi
unpack /filesystem/home/root /root root
unpack /filesystem/boot /boot

# Unpack root at the end, so files are modified before
unpack /filesystem/root /

# Install needed packages
apt-get -y install git wget

# Prepare dirs
sudo -u pi mkdir -p /home/pi/build
ln -s /home/pi /zynthian
rm -rf /usr/lib/lv2
mkdir -p /zynthian/zynthian-plugins/lv2
ln -s /usr/lib/lv2 "/zynthian/zynthian-plugins/lv2"

# Find out zynthian repo url from source line
zynthbox_repo_base_url=$(echo $ZYNTHIANOS_ZYNTHBOX_REPO_SOURCELINE | grep -Eo "(http|https)://[a-zA-Z0-9./?=_%:-]*")
# Find out release name from source line
zynthbox_repo_debian_release_name=$(echo $ZYNTHIANOS_ZYNTHBOX_REPO_SOURCELINE | cut -d " " -f 3)
# Find out latest zynthian-sys url version from package list
zynthian_sys_deb_url=$(curl -Ls "$zynthbox_repo_base_url/dists/bookworm/main/binary-arm64/Packages" | grep -Pzo "Package: zynthian-sys(.|\n)*?Filename: .*\n" | grep -Pao "Filename.*" | head -n 1 | sed "s/Filename: //") # 1. Get list of packages in repo 2. Filter out zynthian-sys packages and it's filenames 3. Get only the filenames 4. Get top most filename 5. Filter the file url
pushd /home/pi/build
    wget "$zynthbox_repo_base_url/$zynthian_sys_deb_url"
    dpkg -i zynthian-sys*.deb
    pushd /home/pi/zynthian-sys/scripts
        bash -x setup_system_rbpi_raspbian_lite_bookworm.sh
    popd
popd

# Cleanup build directory
rm -rf /home/pi/build
rm -f /home/pi/README

# Make root password raspberry
echo root:raspberry | chpasswd

# Allow SSH root login
echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
sed -i 's/PermitRootLogin without-password//g' /etc/ssh/sshd_config

# Disable User Pi
passwd -l pi

